"""
CMake 所需的相关文件mustache模板
"""

PROJECT_CMAKELISTS_TXT = """
######################################################################
# Automatically generated by cppiniter ({{{version}}}) {{{data_time}}}
######################################################################

project ({{{project_name}}})
cmake_minimum_required (VERSION 3.0)

add_subdirectory (src)
add_subdirectory (test)

set(CMAKE_CXX_STANDARD 11)
SET(CMAKE_BUILD_TYPE "Debug")

SET(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g2 -ggdb")
SET(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall")
"""

SRC_CMAKELISTS_TXT = """
######################################################################
# Automatically generated by cppiniter ({{{version}}}) {{{data_time}}}
######################################################################

# add the executable

aux_source_directory(. SRC)

{{#lib}}
add_library({{{project_name}}} ${SRC})
{{/lib}}
{{^lib}}
add_executable ({{{project_name}}} ${SRC})
{{/lib}}

INSTALL(TARGETS {{{project_name}}}
	RUNTIME DESTINATION bin
	LIBRARY DESTINATION lib
	ARCHIVE DESTINATION lib)
"""

TEST_CMAKELISTS_TXT = """
######################################################################
# Automatically generated by cppiniter ({{{version}}}) {{{data_time}}}
######################################################################

# add the executable

aux_source_directory(. SRC)

add_executable (catch ${SRC})

target_link_libraries(catch {{{project_name}}})

INSTALL(TARGETS catch
    RUNTIME DESTINATION bin)
"""

FILES = (PROJECT_CMAKELISTS_TXT, TEST_CMAKELISTS_TXT)
