"""
CMake 所需的相关文件mustache模板
"""

PROJECT_CMAKELISTS_TXT = """\
######################################################################
# Automatically generated by cppiniter ({{{version}}}) {{{date_time}}}
######################################################################

project ({{{project_name}}})
cmake_minimum_required (VERSION 3.0)

add_subdirectory (src)
{{#is_lib}}
add_subdirectory (test)
{{/is_lib}}

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_BUILD_TYPE "Debug")

set(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g2 -ggdb")
set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall")
"""

SRC_CMAKELISTS_TXT = """\
######################################################################
# Automatically generated by cppiniter ({{{version}}}) {{{date_time}}}
######################################################################

# add the executable

aux_source_directory(. SRC)

{{#is_lib}}
add_library({{{project_name}}} SHARED ${SRC})
{{/is_lib}}
{{^is_lib}}
add_executable ({{{project_name}}} ${SRC})
{{/is_lib}}

INSTALL(TARGETS {{{project_name}}}
	RUNTIME DESTINATION bin
	LIBRARY DESTINATION lib
	ARCHIVE DESTINATION lib)
"""

TEST_CMAKELISTS_TXT = """\
######################################################################
# Automatically generated by cppiniter ({{{version}}}) {{{date_time}}}
######################################################################

# add the executable

aux_source_directory(. SRC)

add_executable (catch ${SRC})

target_link_libraries(catch {{{project_name}}})

INSTALL(TARGETS catch
    RUNTIME DESTINATION bin)
"""

README_MD = """\
# {{{project_name}}}
"""

FILES = { "PROJECT_CMAKELISTS_TXT":PROJECT_CMAKELISTS_TXT,
        "SRC_CMAKELISTS_TXT":SRC_CMAKELISTS_TXT,
        "TEST_CMAKELISTS_TXT":TEST_CMAKELISTS_TXT,
        "README_MD":README_MD}
