line-length = 120

[lint]
select = ["E", "F", "W"]
ignore = ["E501"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
docstring-code-format = false
